# Api de ArcGis para Python

## Ciencia de datos con el api de ArcGis para Python

 Vea los datos de nuevas maneras, mejore los resultados operativos y comerciales, y desbloquee todo el potencial de sus datos.

## Importar librerias
Importar las librerias que se van a usar

In [4]:
from arcgis import GIS

import pandas as pd
import matplotlib as plt
import numpy as np

from arcgis.features import SpatialDataFrame

## Conectar a cuenta arcgis online (No es obligatorio)
También se puede hacer uso de contenido público sin necesidad de hacer uso de una cuenta ArcGis

In [2]:
gis=GIS("https://www.arcgis.com","dparra_geek","Esrico123*")

## Importa contenido de arcgis online con el id de ArcGis online
Se toma el contenido por medio del id

In [4]:
item = GIS().content.get("5479b54bd1544e3a9553f40f219da67b")
item

## Toma la primera capa del contenido
El contenido de Hurtos poseé dos capas, que corresponden al mapa base de la ciudad de Bogotá (capa 1) y a la ubicación de los hurtos (capa 0)

In [5]:
flayer = item.layers[0]

## Convierte los datos a un dataFrame de pandas
Los datos de la capa de Hurtos se convierten a un DataFrame de Pandas y se muestra la cabeza del DataFrame

In [7]:
sdf = pd.DataFrame.spatial.from_layer(flayer)
sdf.head()

,ANNO,BARRIO,CARACTERIZACION,CERO_SEIS,COD_DEPTO,CORREGIMIENTO,DANEDEPARTAMENTO,DANEMUNICIPIO,DENELOCALIDAD,DENUNCIAENLINEA,...,SEIS_NUEVE,SHAPE,TARGET_FID,TIPO,TOTAL,URLIMAGEN,VEINTE_VEINTICUATRO,VEREDA,VICTIMAS,ZONA
0,2018,TEUSAQUILLO,HURTO A PERSONAS,1,11,None,11,11001,0.0,N,...,0,"{""x"": -74.06939999999997, ""y"": 4.6236960000000...",1,None,1,http://www.elcolombiano.com/documents/10157/0/...,0,None,None,Rural
1,2018,SAN_BERNARDO,HURTO A PERSONAS,0,11,None,11,11001,0.0,S,...,0,"{""x"": -74.08575399999995, ""y"": 4.5940960000000...",4,None,1,None,0,None,65-M,Rural
2,2018,S.C. LAS ACACIAS,HURTO A CELULARES,0,11,None,11,11001,0.0,S,...,1,"{""x"": -74.05242999999996, ""y"": 4.6517740000000...",5,None,1,None,0,None,24-M,Rural
3,2018,RUBÉN VALLEJO,HURTO A PERSONAS,0,11,None,11,11001,0.0,S,...,0,"{""x"": -74.13422399999996, ""y"": 4.6813730000000...",6,None,1,None,0,None,26-M,Rural
4,2018,RAFAEL URIBE,HURTO A PERSONAS,0,11,None,11,11001,0.0,S,...,0,"{""x"": -74.06899999999996, ""y"": 4.6546440000000...",7,None,1,None,1,None,39-M,Rural

## Agrupar por localidad y el total de hurtos

In [17]:
sdf3=pd.DataFrame(sdf.groupby(['LOCALIDAD'])['TOTAL'].sum())
sdf3

                              TOTAL
LOCALIDAD
LOCALIDAD ANTONIO NARIÑO        165
LOCALIDAD BARRIOS UNIDOS        378
LOCALIDAD BOSA                  398
LOCALIDAD CANDELARIA            188
LOCALIDAD CHAPINERO             962
LOCALIDAD CIUDAD BOLIVAR        316
LOCALIDAD ENGATIVA              755
LOCALIDAD FONTIBON              464
LOCALIDAD KENNEDY               868
LOCALIDAD LOS MARTIRES          406
LOCALIDAD PUENTE ARANDA         397
LOCALIDAD RAFAEL URIBE URIBE    276
LOCALIDAD SAN CRISTOBAL         217
LOCALIDAD SANTA FE              676
LOCALIDAD SUBA                  906
LOCALIDAD TEUSAQUILLO           635
LOCALIDAD TUNJUELITO            208
LOCALIDAD USAQUEN               953
LOCALIDAD USME                  173

## Datos agrupados por la caracterización del hurto

In [19]:
pd.DataFrame(sdf.groupby(['CARACTERIZACION'])['TOTAL'].sum())

                   TOTAL
CARACTERIZACION
HURTO A CELULARES   3679
HURTO A PERSONAS    5662

In [6]:
from bokeh.plotting import figure, output_file, show
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

y=np.random.randint(10, size=10)
x=np.random.randint(15, size=10)


output_file("lines.html")
# add a line renderer with legend and line thickness
p.line(y, x, legend="Temp.", line_width=2)

# show the results
show(p)